# frozen_string_literal: true

source 'https://rubygems.org'

gem 'confidante'
gem 'git'
gem 'google-cloud-resource_manager', '~> 0.37.0'
gem 'google-cloud-resource_manager-v3', '~> 0.3.0'
gem 'iostreams'
gem 'os'
gem 'rake'
gem 'rake_circle_ci'
gem 'rake_git'
gem 'rake_git_crypt'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_ssh'
gem 'rake_terraform'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'rubyzip'
gem 'semantic'
