---
source_directory: "spec/infra/project_hierarchy"
state_file: "%{hiera('project_directory')}/state/project_hierarchy.tfstate"

gcp_credentials: "%{hiera('project_directory')}/config/secrets/gcp/infrablocks-testing-bootstrap.json"
gcp_project_id: "infrablocks-testing"
gcp_folder_id: "274171096401"
gcp_root_project_id: "%{hiera('component')}-%{hiera('deployment_identifier')}-root"
gcp_root_project_name: "%{hiera('component')}-%{hiera('deployment_identifier')}-root"
gcp_management_project_name: "%{hiera('component')}-%{hiera('deployment_identifier')}-mgmt"
gcp_management_project_id: "%{hiera('component')}-%{hiera('deployment_identifier')}-mgmt"
gcp_production_project_name: "%{hiera('component')}-%{hiera('deployment_identifier')}-prod"
gcp_production_project_id: "%{hiera('component')}-%{hiera('deployment_identifier')}-prod"

vars:
  folder_id: "%{hiera('gcp_folder_id')}"
  root_project_name: "%{hiera('gcp_root_project_name')}"
  root_project_id: "%{hiera('gcp_root_project_id')}"
  management_project_name: "%{hiera('gcp_management_project_name')}"
  management_project_id: "%{hiera('gcp_management_project_id')}"
  production_project_name: "%{hiera('gcp_production_project_name')}"
  production_project_id: "%{hiera('gcp_production_project_id')}"
